# Replace ALL occurrences of GITHUB_USERNAME with your actual value
apiVersion: v1
kind: Service
metadata:
  name: student-GITHUB_USERNAME-svc
  labels:
    app: student-app
    student: GITHUB_USERNAME
spec:
  selector:
    app: student-app
    student: GITHUB_USERNAME
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
